# Generated by Django 3.2.20 on 2023-07-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teachermodel_school'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistic.subjectmodel'),
        ),
    ]
