# Generated by Django 3.2.20 on 2023-07-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230714_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(default='', upload_to='upload/student'),
        ),
    ]
